name: Nightly Release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Add nuget to PATH
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: "5.x"
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: "16.7.2"
      - name: Build
        run: |
          MSBuild.exe $Env:GITHUB_WORKSPACE\streamdeck-prismatik.sln /property:Configuration=Release /t:restore
      - name: Publish Nightly
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            streamdeck-prismatik/bin/Release/*
