name: Nightly Release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Add nuget to PATH
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: "5.x"
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: "16.7.2"
      - name: Build
        run: |
          nuget restore streamdeck-prismatik.sln
          MSBuild.exe $Env:GITHUB_WORKSPACE\streamdeck-prismatik.sln /property:Configuration=Release
      - name: Create Distribution Plugin File
        run: |
          curl.exe --output DistributionToolWindows.zip --url https://developer.elgato.com/documentation/stream-deck/distributiontool/DistributionToolWindows.zip
          7z x DistributionToolWindows.zip
          ./DistributionTool.exe -b -i streamdeck-prismatik/bin/Release/de.simonbalzer.prismatik.sdPlugin -o Release
      - name: Publish Nightly
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            Release/streamdeck-prismatik.sdPlugin
